Kotlin/kotlin-by-example

docs-src/index.adoc
docs-src/inheritance.adoc
docs-src/namedArguments.adoc

Please don't hesitate to ask me for any change in the format/structure of the document.
Signed-off-by: Mario Macias <mariomac@gmail.com>

Added some basic examples about inheritance

---

docs-src/nullSafety.adoc

A bit on null safety.  Happy to do more, just want to make sure I'm on the right track.

Null safety

---

_examples/variables.md

Fix naming variables

---

_examples/loops.md

println("Watch out, it's a ${animal.name}")

update for line number 45

---

_examples/destructuring.md

Change second "email" variable name to prevent conflicting variable declaration when running the sample using embedded kotlin in http://kotlinbyexample.org/examples/destructuring

Change second "email" variable name to emailAddress

---

_data/examples.yml
_examples/smartCasts.md

Smart casts

---

_data/examples.yml
_examples/delegationPattern.md

I love the idea of  kotlinbyexample. I think this pattern encourages to follow the reuse principle "composition over inheritance".

Add Example for Delegation Pattern

---

examples/01_introduction/01_Hello world.md

proofread watson

---

examples/02_control_flow/01_When.md

Programming languages are usually referred to in singular

01_When : Kotlin is singular

---

examples/02_control_flow/01_When.md
examples/02_control_flow/02_Loops.md
examples/02_control_flow/03_Ranges.md
examples/02_control_flow/05_Conditional expression.md
examples/05_stdlib/10_associateBy.md

Revised the texts in the Control Flow chapter.

docs: revised Control Flow

---

examples/03_special_classes/00_description.md
examples/03_special_classes/01_Data classes.md
examples/03_special_classes/02_Enum.md
examples/03_special_classes/03_Sealed Classes.md
examples/03_special_classes/04_Object.md

revised texts in the Special classes chapter

docs: revised Special classes 

---

examples/04_functional/01_Higher-Order Functions.md
examples/04_functional/02_Lambdas.md
examples/04_functional/03_extensionFunctions.md

revised text in the Functional chapter.

docs: revised Functional 

---

examples/06_productivity_boosters/00_description.md
examples/06_productivity_boosters/01_namedArguments.md
examples/06_productivity_boosters/02_String Templates.md
examples/06_productivity_boosters/03_Destructuring Declarations.md
examples/06_productivity_boosters/04_Smart Casts.md

Revised the texts in the Productivity Boosters chapter.

docs: revised Productivity Boosters

---

examples/09_Kotlin_JS/01_dynamic.md
examples/09_Kotlin_JS/02_js_function.md
examples/09_Kotlin_JS/03_external.md
examples/09_Kotlin_JS/06_HtmlBuilder.md

Revised the texts in the Kotlin/JS chapter.

docs: revised Kotlin/JS

---

examples/05_stdlib/01_letFunction.md
examples/05_stdlib/02_withFunction.md
examples/05_stdlib/03_filter.md
examples/05_stdlib/04_map.md
examples/05_stdlib/05_existential.md
examples/05_stdlib/06_find.md
examples/05_stdlib/07_firstlast.md
examples/05_stdlib/08_count.md
examples/05_stdlib/09_partition.md
examples/05_stdlib/10_associateBy.md
examples/05_stdlib/11_zip.md
examples/05_stdlib/12_flatMap.md
examples/05_stdlib/13_max.md
examples/05_stdlib/14_sorted.md
examples/05_stdlib/15_Map_getValue.md
examples/05_stdlib/16_getOrElse.md

Revised the text in the Stdlib chapter.

docs: revised Stdlib 

---

examples/07_Delegation/01_delegationPattern.md
examples/07_Delegation/02_DelegatedProperties.md

Revised the text in the Delegation chapter.

docs: revised Delegation

---

examples/01_introduction/04_Null Safety.md

notNull argument on line 26 is not defined. Switch it to a defined variable.

Update 04_Null Safety.md

---

examples/03_special_classes/01_Data classes.md

Update 01_Data classes.md

---

examples/03_special_classes/03_Sealed Classes.md

Added some more info surrounding the nuance of the sealed keyword.

Update 03_Sealed Classes.md

---

examples/02_control_flow/04_Equality Checks.md

The next screen (Conditional Expressions) says that Kotlin does not support ternary operators so I believe it does not make sense to use ternary in the description to explain this concept.
I would also recommend swapping the Conditional Expressions page and Equality Checks page in the ordering.

Update 04_Equality Checks.md

---

examples/09_Kotlin_JS/06_HtmlBuilder.md

Enhance HTML Builder example

---

examples/05_Collections/10_associateBy.md

Add an example describing the difference between `associateBy()` and `groupBy()`

Add an example of associateBy()

---

examples/05_Collections/12_flatMap.md

This example will help in understanding the exact difference between FlatMap and map.

FaltMap: Add detailed example with explanation.

---

examples/03_special_classes/01_Data classes.md

I wanted to clarify some things on this page which might help people understand more of the concepts:
- Show that the data class can override any default method (such as equals) as well
- Make it clear that instances' hashCodes are only equal iff they have exactly the same attributes, not if the objects are structurally equal
- Show that the copy method really does create a new instance by checking referential equality with the copied object
(- Also remove () from one of the hashCodes in the plain text to make it consistent)

Update Data classes.md

---

examples/03_special_classes/02_Enum.md

This will make it more clear that the operation carried out in containsRed() is a bitwise and operation and not something else. Also, it seems that yellow doesn't really serve a purpose otherwise.

Add containsRed() check for yellow

---

.github/workflows/verify-samples.yml
examples/01_introduction/03_Variables.md
examples/01_introduction/04_Null Safety.md

Reverts Kotlin/kotlin-by-example#155

Revert "chore(samples): mark samples novalidate"

---

.github/workflows/verify-samples.yml
examples/01_introduction/03_Variables.md
examples/01_introduction/04_Null Safety.md

Reverts Kotlin/kotlin-by-example#156

Revert "Revert "chore(samples): mark samples novalidate""

---

examples/03_special_classes/02_Enum.md

Enum are like static classes. There is no instance.

fix: there is not a such thing as "enum instance"

---

examples/08_productivity_boosters/02_String Templates.md

Update 02_String Templates.md

---

README.md

Add a JetBrains official badge to the Readme file.

Add JetBrains official badge to Readme
